name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install Maven Depedencies
        run: mvn install
      - name: Run Tests
        run: mvn clean test -Dtest=*

